title: Conservation Data Framework
description: Zentrale Dokumentation des Conservation Data Frameworks
theme: just-the-docs
color_scheme: n4o

url: "https://nfdi4objects.github.io"
baseurl: "/n4o_conservation_data_framework"

# Enable or disable the side/mobile menu globally
nav_enabled: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

