title: NFDI4Objects Conservation Data Framework
description: Zentrale Dokumentation des Conservation Data Frameworks
remote_theme: pmarsceill/just-the-docs

plugins:
  - jekyll-remote-theme

url: "https://nfdi4objects.github.io"
baseurl: "/n4o_conservation_data_framework"

nav_enabled: true
search_enabled: true
back_to_top: true
back_to_top_text: "Back to top"
